project:
  type: website

website:
  title: "Meu Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/joaobtj

format:
  html:
    theme: minty
    css: styles.css
    lang: pt


